name: Java Selenium CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Exécute tous les jours à 12h00 Paris (10h00 UTC)
    - cron: '0 10 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Run tests with Maven
      run: mvn clean test
